version: '2'
services:
  default:
    links:
      - administration-portal:administration-portal
  administration-portal:
    image: ${REPOSITORY_URI}:${COMMIT_HASH}
    environment:
      - NODE_ENV=local
    ports:
      - 3000:3000